export enum EnvKey {
  AccessTokenTtlSeconds = "ACCESS_TOKEN_TTL_SECONDS",
  AiApiKey = "AI_API_KEY",
  AiBaseUrl = "AI_BASE_URL",
  AiModel = "AI_MODEL",
  AiProvider = "AI_PROVIDER",
  CorsOrigin = "CORS_ORIGIN",
  DatabaseUrl = "DATABASE_URL",
  Host = "HOST",
  JwtSecret = "JWT_SECRET",
  Port = "PORT",
  R2AccountId = "R2_ACCOUNT_ID",
  R2AccessKeyId = "R2_ACCESS_KEY_ID",
  R2BucketName = "R2_BUCKET_NAME",
  R2PublicUrl = "R2_PUBLIC_URL",
  R2SecretAccessKey = "R2_SECRET_ACCESS_KEY",
  RedisUrl = "REDIS_URL",
}
